name: Deploy to vercel
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: dkershner6/vercel-set-env-action@v3
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: builder-dashboard
          envVariableKeys: COOKIE_SECRET,NEXT_PUBLIC_TURNSTILE_SITE_KEY,TURNSTILE_SECRET_KEY
        env:
          COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
          TARGET_COOKIE_SECRET: preview,development,production
          TYPE_COOKIE_SECRET: encrypted
          NEXT_PUBLIC_TURNSTILE_SITE_KEY: ${{ secrets.NEXT_PUBLIC_TURNSTILE_SITE_KEY }}
          TARGET_NEXT_PUBLIC_TURNSTILE_SITE_KEY: production
          TYPE_NEXT_PUBLIC_TURNSTILE_SITE_KEY: plain
          TURNSTILE_SECRET_KEY: ${{ secrets.TURNSTILE_SECRET_KEY }}
          TARGET_TURNSTILE_SECRET_KEY: production
          TYPE_TURNSTILE_SECRET_KEY: encrypted
      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-project-name: builder-dashboard
